version: "2"         # required to adjust maintainability checks
exclude_patterns:
  - "!**/test/"
  - "!db/**/*"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: true
  method-complexity:
    enabled: true
  method-count:
    enabled: false
  method-lines:
    enabled: true
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: true
plugins:
  rubocop:
    channel: 'rubocop-0-92'
    enabled: true
    config:
      file: .rubocop.yml
